--SQLQuery0-CREATE DATABASE.sql
CREATE DATABASE PD_411_SQL_HW
ON
(
	NAME		=	PD_411_SQL_HW,
	FILENAME	=	'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Data\PD_411_SQL_HW.mdf',
	SIZE		=	8MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	5MB
)

LOG ON
(
	NAME		=	PD_411_SQL_HW_Log,
	FILENAME	=	'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Data\PD_411_SQL_HW_log.ldf',
	SIZE		=	8MB,
	MAXSIZE		=	500MB,
	FILEGROWTH	=	8MB
);
GO